"""WebSocket progress-message schema (H-0069).

Single source of truth for the ``/ws/jobs/{job_id}/progress`` wire
format.  Four message variants are expressed as Pydantic models and
combined into a discriminated union so parsers (`TypeAdapter(WsMessage)
.validate_json`) dispatch on the ``type`` field without ambiguity.

Serialization is ``model_dump(exclude_none=True)`` / ``model_dump_json
(exclude_none=True)`` so Optional fields (``fold_results``,
``trial_results``) only appear on the wire when populated — the output
is byte-identical to the hand-rolled ``json.dumps`` that used to live
inside ``ws/progress.py::send_progress``.

The browser receives this schema via ``schema.d.ts`` (generated by
``openapi-typescript``), so the frontend imports ``WsMessage`` instead
of maintaining a hand-written duplicate.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class WsFoldResult(BaseModel):
    """One cross-validation fold result emitted inside ``WsProgress`` (H-0047).

    Only ``fold`` (the 0-based index) is fixed.  Per-metric values flow
    through as ``extra='allow'`` because the set of metric keys is
    task-dependent: a regression run emits ``rmse`` / ``r2`` / ``mae``,
    a binary classification run emits ``auc`` / ``logloss`` / ``accuracy``,
    etc.  Hard-coding the shape would force every metric name into the
    contract and couple the schema to a single backend.
    """

    model_config = ConfigDict(extra="allow")

    fold: int


class WsTrialResult(BaseModel):
    """One Optuna trial result emitted inside ``WsProgress`` (H-0055)."""

    model_config = ConfigDict(extra="allow")

    number: int
    score: float | None
    state: str
    best_score: float | None


class WsProgress(BaseModel):
    """Live training / tuning progress (H-0047 fold_results, H-0055 trial_results)."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["progress"]
    job_id: str
    current: int
    total: int
    message: str
    fold_results: list[WsFoldResult] | None = None
    trial_results: list[WsTrialResult] | None = None


class WsCompleted(BaseModel):
    """Terminal success message — closes the WS connection client-side."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["completed"]
    job_id: str
    message: str = "Completed."


class WsError(BaseModel):
    """Terminal failure message — closes the WS connection client-side."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["error"]
    job_id: str
    message: str
    code: str = "BACKEND_ERROR"


class WsPing(BaseModel):
    """30-second keepalive ping (H-0058).

    Carries no payload beyond the discriminator and the job id — clients
    may ignore it.
    """

    model_config = ConfigDict(extra="forbid")

    type: Literal["ping"]
    job_id: str


WsMessage = Annotated[
    WsProgress | WsCompleted | WsError | WsPing,
    Field(discriminator="type"),
]


__all__ = [
    "WsCompleted",
    "WsError",
    "WsMessage",
    "WsPing",
    "WsProgress",
]
